apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quest-mode-ci
  namespace: quest-mode
  labels:
    app: quest-mode-ci
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: main
  workspaces:
    - name: source
  tasks:
    - name: fetch-source
      taskRef:
        name: fetch-source
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: source
          workspace: source
    - name: lint
      taskRef:
        name: go-lint
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: source
    - name: test
      taskRef:
        name: go-test
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: source
    - name: fe
      taskRef:
        name: frontend-build
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: source
    - name: build
      taskRef:
        name: docker-build
      runAfter:
        - test
        - fe
      workspaces:
        - name: source
          workspace: source
