apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-source-pvc
  namespace: quest-mode
  labels:
    app: quest-mode-ci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
