apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quest-mode-workspace
  namespace: quest-mode
  labels:
    app.kubernetes.io/name: tekton-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
