apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quest-postgres-pvc
  namespace: quest-mode
  labels:
    app.kubernetes.io/name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
